---
- name: Set up Apache Server
  hosts: michael@192.168.65.2
  become: true
  tasks:
    - name: Update repository index for Ubuntu
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution_version == "Ubuntu"

    - name: Installing Apache
      ansible.builtin.apt:
        name: apache2
      notify:
        - Start Apache

    - name: Configure Timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: Create index.php file
      ansible.builtin.copy:
        content: |
          <?php
          echo date("F d, Y h:i:s A e", time());
        dest: /var/www/html/index.php
        owner: michael
        group: adm
        mode: "0644"
      notify:
        - Restart Apache

  handlers:
    - name: Start Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
