---
- name: Set up Apache Server
  hosts: michael@192.168.65.2
  become: yes

  tasks:
    - name: update repository index for Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution_version == "Ubuntu"

    - name: Installing Apache
      apt:
        name: apache2
      notify:
        - Start Apache

    - name: Configure Timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: Create index.php file
      copy:
        content: |
          <?php
          echo date("F d, Y h:i:s A e", time());
        dest: /var/www/html/index.php
      notify:
        - Restart Apache

  handlers:
    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
