---
- name: Installing Apache
  hosts: all
  become: true
  tasks:
    - name: Install apache and php for Ubuntu servers
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install httpd and php for Fedora servers
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        update_cache: true
      when: ansible_distribution == "Fedora"
