---

- name: Maintaining the nodes
  hosts: all
  become: true
  tasks:

    - name: Install package updates (Fedora)
      dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "Fedora"

    - name: Install package updates (Ubuntu)
      apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- name: Web_servers
  hosts: web_servers
  become: true
  tasks:
    - name: Install apache and php for Ubuntu servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_distribution == "Ubuntu"

    - name: Install httpd and php for Fedora servers
      dnf:
        name:
          - httpd
          - php
        update_cache: true
      when: ansible_distribution == "Fedora"

- name: Db_servers
  hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb package (Fedora)
      dnf:
        name: mariadb
      when: ansible_distribution == "Fedora"

    - name: Install mariadb package (Ubuntu)
      apt:
        name: mariadb-server
      when: ansible_distribution == "Ubuntu"

- name: File_servers
  hosts: file_servers
  become: true
  tasks:
    - name: Install samba package
      package:
        name: samba
