---

- name: Maintaining the nodes
  hosts: all
  become: true
  tasks:
    - name: Install package updates (Fedora)
      tags: always
      dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "Fedora"

    - name: Install package updates (Ubuntu)
      tags: always
      apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- name: Adding Terraform to Workstation
  hosts: workstation
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.3/terraform_1.6.3_darwin_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: "0755"
      owner: root
      group: root


- name: Web_servers
  hosts: web_servers
  become: true
  tasks:
    - name: Install apache and php for Ubuntu servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_distribution == "Ubuntu"

    - name: Install httpd and php for Fedora servers
      tags: apache,httpd,fedora
      dnf:
        name:
          - httpd
          - php
        update_cache: true
      when: ansible_distribution == "Fedora"

    - name: Copy default site
      tags: apache, apache2, httpd
      ansible.builtin.copy:
        src: default-site.html
        dest: /var/www/html/ansindex.html
        owner: michael
        group: adm
        mode: "0644"

- name: Db_servers
  hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb package (Fedora)
      tags: db,maria,fedora
      dnf:
        name: mariadb
      when: ansible_distribution == "Fedora"

    - name: Install mariadb package (Ubuntu)
      tags: db,maria,ubuntu
      apt:
        name: mariadb-server
      when: ansible_distribution == "Ubuntu"

- name: File_servers
  hosts: file_servers
  become: true
  tasks:
    - name: Install samba package
      tags: samba
      package:
        name: samba
